name: flutter_background
description: flutter background + bar
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mpris:
    git:
      url: https://github.com/FlafyDev/dart-mpris
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_staggered_animations: ^1.1.1
  hooks_riverpod: ^2.3.6
  hyprland_ipc:
    git: 
      url: https://github.com/flafydev/hyprland_ipc.git
  file: ^7.0.0
  intl: ^0.18.1
  dbus: ^0.7.8
  path_drawing: ^1.0.1

dev_dependencies:
  custom_lint: ^0.5.6
  riverpod_lint: ^2.3.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
   - assets/
